server:
  port: 8765

spring:
  application:
    name: zuul-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:8761}/eureka/
    register-with-eureka: true